// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfjzhagucbiyxlsspzpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmanpoYWd1Y2JpeXhsc3NwenB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDM2MjYsImV4cCI6MjA3MzExOTYyNn0.H3bHxSJxbKqhdAMXECe36MdQ8qyGefGxVmJhNucxqzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});